upstream backend_servers {
    server 172.17.0.3:8080;
    server 172.17.0.4:8080;
}

server {
    listen 80;

    location / {
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Connection close;

        proxy_buffering off;
        proxy_request_buffering off;

        add_header Content-Type text/plain;

        proxy_pass http://backend_servers;
    }
}
